name: test_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.3
  freezed: ^2.1.0+1
  mask_text_input_formatter: ^2.4.0
  get_it: ^7.2.0
  dio: ^4.0.6
  cupertino_icons: ^1.0.5
  firebase_crashlytics: ^2.8.13
  firebase_core: ^1.24.0
  auto_route: ^5.0.1
  dropdown_button2: ^1.8.4
  easy_localization: ^3.0.1
  retrofit: ^3.3.1
  injectable: ^1.5.3
  freezed_annotation: ^2.1.0
  path_provider: ^2.0.11
  json_annotation: ^4.7.0
  provider: ^6.0.3
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  auto_route_generator: ^5.0.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/images/svg/
    - assets/images/img/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
